version: "3.1"

services:
  database:
    container_name: test-db
    image: postgres

  bot:
    container_name: devcordbot
    image: jkoenig134/devcordbot
    volumes:
      - .env:/usr/app/.env
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - database